### ISSUE TITLE
AUR package

### ISSUE THREAD

**Issue by NikitaIvanovV** [MaxVerevkin/river-luatile#1]
I want to let you know that I have made a package for your program: https://aur.archlinux.org/packages/river-luatile-git

If you want, you can mention it in the README.md, so Arch Linux users can easily install it.

**Comment by MaxVerevkin** [comment]
Thank you, updated my README :)

BTW I pushed an update which adds `libxkbcommon` as a dependency.

**Comment by NikitaIvanovV** [comment]
Added libxkbcommon as a dependency in AUR package.

**Comment by MaxVerevkin** [comment]
`libxkbcommon` was removed as a dependency a while ago.
