### ISSUE TITLE
Rivertile layout example

### ISSUE THREAD

**Issue by ghost** [MaxVerevkin/river-luatile#2]
Configuring layouts in lua is great! Thanks for this.
Didn't know where else to put this.. For anyone looking for a more exact copy of rivertile, see [here](https://codeberg.org/KMIJPH/dotfiles/src/branch/main/config/river-luatile/layout.lua).

Cheers

**Comment by Cybolic** [comment]
For anyone wondering where that file went, here's the [last revision of it](https://codeberg.org/KMIJPH/dotfiles/src/commit/0f46cae89c60e462121c53843df8a18a6e6bf430/config/river-luatile/layout.lua).
