### ISSUE TITLE
Allow setting layout_name dynamically

### ISSUE THREAD

**Issue by pinpox** [MaxVerevkin/river-luatile#4]
Waybar added a module called `river/layout` which allow showing the current layouts name. In `river-luatile` this seems to be hardcoded [here](https://github.com/MaxVerevkin/river-luatile/blob/0ae8e1ca68417878674469def3c861a148fac867/src/main.rs#L55)

Would it be possible to make this configurable form within the lua code?

I have implemented a `layout_switch()` function in my lua code wich works as expected, it would be nice to be able to update the current layout in the status bar.

**Comment by MaxVerevkin** [comment]
I don't know what is the cleanest way to add this feature. I suppose `handle_layout` can return not only a list of rectangles but also some metadata? Something like

```lua
local retval = { layout_name = "my awesome layout" }
--
--
return retval
```

**Comment by pinpox** [comment]
Either that or you could implement an additional function that gets called, something  like `get_metadata()`. Up to you to decide, either way there should probably be a default value so we don't break backward-compatiblity of existing layouts.

**Comment by MaxVerevkin** [comment]
Another option is setting a global variable:

```lua
LAYOUT_NAME = "..."
```

This is IMO the simplest one. But I don't really prefer any of these. Would you like to send a PR?

**Comment by pinpox** [comment]
Having a global varible is a problem if I have multiple outputs with different layouts set, isn't it? I can send a PR when we decide on one of the above.

I currently have three outputs and a keybind to toggle diffent layouts for each output. My (still very messy) layout code is [here](https://gist.github.com/pinpox/b1d300c21a90dc4f8073a9d34369df46)

**Comment by MaxVerevkin** [comment]
> Having a global varible is a problem if I have multiple outputs with different layouts set, isn't it?

Yeah, good catch.

> I can send a PR when we decide on one of the above.

Awesome. You can choose whichever is cleaner/easier to implement.
